# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jon T. Scott
email: JonScott20@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jon T. Scott is a computer science student at Cal Poly San Luis Obispo.
  He is an aspiring software developer who takes pride in his work and enjoys contributing to cohesive team projects.
  Born and raised in the small town of Hailey, Idaho, he relocated to California for the booming tech industry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  JonScott20

# Build settings
markdown: kramdown
